### ISSUE TITLE
teachers panel: new course with submission deadlines

### ISSUE THREAD

**Issue by meling** [hfurubotten/autograder#21]
The new course page should allow entry of deadlines for each of the lab assignments, so that this can be used to compute the number of slip days. Maybe there is a calendar dropdown thing that can be used, or do we need to make our own or just use plain text that is checked. The deadline should also include the time, e.g. 11:59 am.

These deadlines should also be possible to change, since sometimes official UiS schedules change too.

**Comment by hfurubotten** [comment]
Solved in commit 432ea91b358ad26cb9004a791185cfccad601d03 where the deadlines can be put changes in the setting page on teachers panel.
