### ISSUE TITLE
teachers panel: possibility to add notes to each lab for each student/group

### ISSUE THREAD

**Issue by tormoder** [hfurubotten/autograder#24]
Just a small feature request.

It would be nice to have a text area so its possible to add notes to each lab for each student/group. Notes should only be visible to teachers. This will ease the approval process if there are several student assistants and teachers. It would be convenient to add notes like:

```
Weak implementation, approved under doubt. Both group members should be present next time. 
```

It will additionally serve as a history that is useful during a lab exam or a final grading process.

**Comment by hfurubotten** [comment]
Notes for each lab on students and groups added in commit a49907b6076ddf5ffd493e9feb9b32308113d5ac
