### ISSUE TITLE
Upgrade to boltdb

### ISSUE THREAD

**Issue by hfurubotten** [hfurubotten/autograder#34]
To make the storage solution more usable and better to manage, an upgrade which uses a simple database, like boltdb, is needed.

**Comment by meling** [comment]
There are still a lot of code that depends on diskv, much of which is marked as deprecated. Is this done yet? 

    % grep -r 'diskv' *
    README.md:[diskv]: https://github.com/hfurubotten/diskv
    game/entities/tokens.go:	"github.com/hfurubotten/diskv"
    game/entities/tokens.go:var tokenstore = diskv.New(diskv.Options{
    game/entities/tokens.go:	BasePath:     "diskv/tokens",
    git/groups.go:	"github.com/hfurubotten/diskv"
    git/groups.go:	store *diskv.Diskv
    git/groups.go:var groupstore map[string]*diskv.Diskv
    git/groups.go:func GetGroupStore(org string) *diskv.Diskv {
    git/groups.go:		groupstore = make(map[string]*diskv.Diskv)
    git/groups.go:		groupstore[org] = diskv.New(diskv.Options{
    git/groups.go:			BasePath:     global.Basepath + "diskv/groups/" + org + "/",
    git/groups_test.go:	return os.RemoveAll(global.Basepath + "diskv/groups/" + course + "/")
    git/members.go:	"github.com/hfurubotten/diskv"
    git/members.go:var userstore *diskv.Diskv
    git/members.go:// getUserstore will return the diskv object to access users stored in memory and on disk.
    git/members.go:func getUserstore() *diskv.Diskv {
    git/members.go:		userstore = diskv.New(diskv.Options{
    git/members.go:			BasePath:     global.Basepath + "diskv/users/",
    git/members_test.go:	if err := os.RemoveAll(global.Basepath + "diskv/users/"); err != nil {
    git/members_test.go:	return os.RemoveAll(global.Basepath + "diskv/tokens/")
    git/organisation.go:	"github.com/hfurubotten/diskv"
    git/organisation.go:var orgstore *diskv.Diskv
    git/organisation.go:// GetOrganizationStore returns a diskv object used to store the organization object to memory and disk.
    git/organisation.go:func GetOrganizationStore() *diskv.Diskv {
    git/organisation.go:		orgstore = diskv.New(diskv.Options{
    git/organisation.go:			BasePath:     global.Basepath + "diskv/orgs/",
    git/tokens.go:	"github.com/hfurubotten/diskv"
    git/tokens.go:var tokenstore *diskv.Diskv
    git/tokens.go:func getTokenStore() *diskv.Diskv {
    git/tokens.go:		tokenstore = diskv.New(diskv.Options{
    git/tokens.go:			BasePath:     global.Basepath + "diskv/tokens",
    migration/DBMigration/diskvtobolt.go:	"github.com/hfurubotten/diskv"
    migration/DBMigration/diskvtobolt.go:var optionstore = diskv.New(diskv.Options{
    migration/DBMigration/diskvtobolt.go:	BasePath:     "diskv/options/",
    migration/DBMigration/diskvtobolt.go:func GetCIStorage(course, user string) *diskv.Diskv {
    migration/DBMigration/diskvtobolt.go:	return diskv.New(diskv.Options{
    migration/DBMigration/diskvtobolt.go:		BasePath:     "diskv/CI/" + course + "/" + user,
